spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    url: jdbc:mysql://localhost:3306/hisDb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: jayesh
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
       hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format-sql: true